// Generated by Wrangler on Mon Mar 25 2024 11:59:17 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_SIGN_IN_URL: string;
	CLERK_SIGN_UP_URL: string;
	CLERK_AFTER_SIGN_IN_URL: string;
	CLERK_AFTER_SIGN_UP_URL: string;
}
