// Generated by Wrangler on Tue Mar 26 2024 10:50:23 GMT-0700 (Pacific Daylight Time)
// by running `wrangler types`

interface Env {
	CLERK_PUBLISHABLE_KEY: string;
	CLERK_SECRET_KEY: string;
	CLERK_SIGN_IN_URL: string;
	CLERK_SIGN_UP_URL: string;
	CLERK_AFTER_SIGN_IN_URL: string;
	CLERK_AFTER_SIGN_UP_URL: string;
	SUPABASE_URL: string;
	SUPABASE_ANON_KEY: string;
}
